--DROP TABLE CATALOG;

--DROP TABLE SUPPLIERS;

--DROP TABLE PARTS;

CREATE TABLE SUPPLIERS (
    SID INTEGER PRIMARY KEY,
    SNAME VARCHAR(255),
    CITY VARCHAR(255)
);

CREATE TABLE PARTS (
    PID INTEGER PRIMARY KEY,
    PNAME VARCHAR(255),
    COLOR VARCHAR(255)
);

CREATE TABLE CATALOG (
    SID INTEGER,
    PID INTEGER,
    COST REAL,
    PRIMARY KEY (SID, PID),
    FOREIGN KEY (SID) REFERENCES SUPPLIERS(SID),
    FOREIGN KEY (PID) REFERENCES PARTS(PID)
);
